### ISSUE TITLE
Fundamental flaw not only in the game, but in the very nature of its physics

### ISSUE THREAD

**Issue by Ozzie19** [ddey123/TicTacToe#1]

**Comment by Debayan-D** [comment]
Well Mr. Ozzie19 the entire aim of this game was to make sure that the computer would always win and the highest attainable result would be a draw. But thank you for concern.

**Comment by Ozzie19** [comment]
Unbelievable service. I have POLITELY raised an issue which needs to be fixed immediately for this unplayable game. I do NOT care that I can just play tic tac toe against my mum and always win. I do NOT care that you are not paid and work alone. Your game is UNPLAYABLE, and you should be ASHAMED. I will be suing for mental trauma.
GOOD DAY SIR

**Comment by Ozzie19** [comment]
The fact that you have not responded within 9 HOURS speaks volumes. Thanks ddey123, I will make sure to encourage others to not use your services. Absolutely TERRIBLE customer satisfaction (I know it’s free, shut up no one asked). 0/10 would only recommend to my worst enemies. Ddey123, I recommend you this game.
Thanks for NOTHING.
Sincerely,
A very disappointed dog

**Comment by Debayan-D** [comment]
Ok Mr Ozzie19 but I am very sure that you are aware of the fact that I am at school during those times. If you aren't aware of this, the times I am unavailable are from 9-3.

**Comment by Ozzie19** [comment]
Ok well then you are clearly TERRIBLE at maths. The hours 9-3 are just 6 hours, yet you didn’t respond for NINE. WHOLE. HOURS. 
WHERE IW THE COMMITMENT TO SERVE?
WHERE IS THE HELPFUL ATTITUDE?
Do me a favour and don’t ever comment on my brilliant tic tac toe game eve again. You have raised a pointless issue about the AI which is not my fault. 
Leave me alone, I am trying to eat my super noodles toenails flavour in peace.

**Comment by Debayan-D** [comment]
Ok weird guy. Eat ur toenail noodles you Turkish Greek!
